services:
  postgres:
    image: postgres:15-alpine
    restart: "always"
    environment:
      # Superuser username/password
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: superpassword
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"
      - "./postgres-firstrun/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh:ro"
    networks:
      frontapp:
        ipv4_address: 172.25.0.11

  redis:
    image: redis:7
    networks:
      frontapp:
        ipv4_address: 172.25.0.12
    volumes:
      - "./redis-data:/data"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: "always"
    command: 'redis-server --save 60 1 --loglevel warning'

networks:
  frontapp:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1
